---
  - name: make user
    user: name={{user}} group={{group}}

  - name: make .ssh dir
    file: state=directory path=/home/{{user}}/.ssh owner={{user}} group={{group}} mode=0700

  - name: set up epel
    get_url: dest=/tmp/epel-release.rpm  url=http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

  - name: install epel
    yum: pkg=/tmp/epel-release.rpm state=installed

  - name: set up remi
    get_url: dest=/tmp/remi-release.rpm  url=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

  - name: install remi
    yum: pkg=/tmp/remi-release.rpm state=installed

  - name: yum
    yum: pkg={{item}} state=installed enablerepo=remi,epel
    with_items:
      th_items: 
      - "@development"
      - expat
      - expat-devel
      - git
      - openssl-devel
      - postfix
      - rpm
      - rpm-build
      - screen
      - wget
      - zlib-devel
      - dstat
      - htop
      - iotop

  - name: stop iptables
    service: name=iptables state=stopped  enabled=no

